name: continuous-integration

on:
  push:
    branches:
      - main

env:
  AZURE_WEBBAPP_NAME: PosiTicks-staging

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Unit Tests
        run: dotnet test --filter FullyQualifiedName~UnitTests ./PosiTicks

      - name: Acceptance Tests
        run: dotnet test --filter FullyQualifiedName~AcceptanceTests ./PosiTicks
      
      - name: publish
        run: dotnet publish ./PosiTicks/Server --configuration Release --output ./output
      
      - name: Deploy to Azure Web Apps using publish profile creds
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.azureWebAppPublishProfile}}
          package: output